- name: Install haproxy
  apt:
    state: present
    name: haproxy
    update_cache: yes
  become: yes

- name: Deploy /etc/haproxy/haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: Restart haproxy
