- name: Create {{ patroni.cfg_dir }} directory
  file:
    state: directory
    path: "{{ patroni.cfg_dir }}"
    owner: "{{ patroni.user }}"
    group: "{{ patroni.group }}"
    mode: 0750
  become: yes

- name: Create {{ patroni.raft_dir }} directory
  file:
    state: directory
    path: "{{ patroni.raft_dir }}"
    owner: "{{ patroni.user }}"
    group: "{{ patroni.group }}"
    mode: 0750
  become: yes

- name: Deploy {{ patroni.cfg_dir }}/config.yml template
  template:
    src: config.yml.j2
    dest: "{{ patroni.cfg_dir }}/config.yml"
    owner: "{{ patroni.user }}"
    group: "{{ patroni.group }}"
    mode: 0640
  become: yes
