# - name: Disable create_main_cluster
#   lineinfile:
#     path: /etc/postgresql-common/createcluster.conf
#     line: create_main_cluster = false
#     create: yes
#   become: yes

- name: Install Postgres
  apt:
    state: present
    name:
      - postgresql-common
      - postgresql-{{ postgres.version }}
      - postgresql-server-dev-{{ postgres.version }}
    update_cache: yes
  become: yes

- name: Install Python and friends
  apt:
    state: present
    name:
      - "{{ python.basename }}-dev"
      - "{{ python.basename }}-pip"
      - "{{ python.basename }}-psycopg2"
    update_cache: yes
  become: yes

- name: Install virtualenv by pip
  pip:
    state: present
    name: virtualenv
    executable: "{{ python.pip.basename }}"
  become: yes

- name: Install Patroni (and Raft)
  pip:
    state: present
    name:
      # - psycopg2-binary
      - patroni[raft]
    virtualenv: "{{ patroni.venv_dir }}"
    virtualenv_python: "{{ python.binary }}"
  become: yes

- name: Create {{ patroni.cfg_dir }} directory
  file:
    state: directory
    path: "{{ patroni.cfg_dir }}"
    owner: "{{ patroni.user }}"
    group: "{{ patroni.group }}"
    mode: 0750
  become: yes

- name: Deploy {{ patroni.cfg_dir }}/config.yml template
  template:
    src: config.yml.j2
    dest: "{{ patroni.cfg_dir }}/config.yml"
    owner: "{{ patroni.user }}"
    group: "{{ patroni.group }}"
    mode: 0640
  become: yes

- name: Load the software watchdog module
  modprobe:
    state: present
    name: softdog
  become: yes

- name: Give postgres ownership of the watchdog
  file:
    path: /dev/watchdog
    owner: "{{ postgres.user }}"
  become: yes

- name: Deploy /etc/systemd/system/patroni.service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: 0640
  become: yes
