- name: Install postgresql-common
  apt:
    state: present
    name:
      - postgresql-common
    update_cache: yes
  become: yes

- name: Disable create_main_cluster
  lineinfile:
    path: /etc/postgresql-common/createcluster.conf
    line: create_main_cluster = false
    create: yes
  become: yes

- name: Install postgresql-{{ postgres.version }}
  apt:
    state: present
    name:
      - postgresql-{{ postgres.version }}
      - postgresql-server-dev-{{ postgres.version }}
    update_cache: yes
  become: yes

- name: Install Python and friends
  apt:
    state: present
    name:
      - "{{ python.basename }}-dev"
      - "{{ python.basename }}-pip"
      - "{{ python.basename }}-psycopg2"
    update_cache: yes
  become: yes

- name: Install virtualenv by pip
  pip:
    state: present
    name: virtualenv
    executable: "{{ python.pip.basename }}"
  become: yes

- name: Install patroni and friends
  pip:
    state: present
    name:
      - psycopg2-binary
      - patroni[raft]
    virtualenv: "{{ patroni.venv_dir }}"
    virtualenv_python: "{{ python.binary }}"
  become: yes

- name: Add the software watchdog module
  modprobe:
    state: present
    name: softdog
  become: yes

- name: Give postgres ownership of the watchdog
  file:
    path: /dev/watchdog
    owner: "{{ postgres.user }}"
  become: yes
