- name: Assert debian bionic
  assert:
    that:
      - ansible_os_family == "Debian"
      - ansible_distribution_release == "bionic"

- name: Include common variables
  include_vars:
    file: main.yml

- name: Include family/distribution variables
  include_vars:
    file: "{{ ansible_os_family }}/{{ ansible_distribution_release }}/main.yml"

- name: Install postgres and patroni
  include_tasks: install.yml

- name: Configure postgres and patroni
  include_tasks: configure.yml

# - name: Start patroni
#   include_tasks: start.yml
