- name: Deploy /etc/systemd/system/patroni.service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: 0640
  become: yes

- name: Start and enable patroni
  systemd:
    name: patroni
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
